CREATE SEQUENCE IF NOT EXISTS category_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS product_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE category
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                             NOT NULL,
    description TEXT,
    CONSTRAINT category_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE category IS 'Stores product categories.';
COMMENT ON COLUMN category.id IS 'Unique identifier for the category (Primary Key)';
COMMENT ON COLUMN category.name IS 'Name of the category (Unique)';
COMMENT ON COLUMN category.description IS 'Description of the category';

CREATE TABLE product
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                             NOT NULL,
    description       TEXT,
    available_quantity INTEGER DEFAULT 0                        NOT NULL,
    price             numeric(10, 2)                           NOT NULL,
    category_id       INTEGER,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE product IS 'Stores information about products.';
COMMENT ON COLUMN product.id IS 'Unique identifier for the product (Primary Key)';
COMMENT ON COLUMN product.name IS 'Name of the product';
COMMENT ON COLUMN product.description IS 'Description of the product';
COMMENT ON COLUMN product.available_quantity IS 'Number of units currently in stock (must be non-negative)';
COMMENT ON COLUMN product.price IS 'Price of the product (must be non-negative)';
COMMENT ON COLUMN product.category_id IS 'Links to the product''s category (Foreign Key)';

ALTER TABLE category
    ADD CONSTRAINT category_name_key UNIQUE (name);

ALTER TABLE product
    ADD CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL;