spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
      username: mongodb
      password: mongodb
server:
  port: 8090
