spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_microservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Initial version"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:mk.orderservice.kafka.OrderConfirmation
server:
  port: 8070

application:
  config:
    customer-service-url: http://localhost:8222/api/v1/customers
    payment-service-url: http://localhost:8222/api/v1/payments
    product-service-url: http://localhost:8222/api/v1/products