spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_microservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Initial version"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8050
